insert into posts (title, img, content, author_id) values ('challenge', 'http://dummyimage.com/159x218.jpg/ff4444/ffffff', 'Optimized reciprocal installation', 1);
insert into posts (title, img, content, author_id) values ('Enhanced', 'http://dummyimage.com/131x132.png/dddddd/000000', 'Reverse-engineered systemic access', 2);
insert into posts (title, img, content, author_id) values ('uniform', 'http://dummyimage.com/195x120.jpg/cc0000/ffffff', 'Stand-alone incremental Graphic Interface', 3);
insert into posts (title, img, content, author_id) values ('support', 'http://dummyimage.com/148x169.bmp/dddddd/000000', 'Team-oriented 4th generation encryption', 4);
insert into posts (title, img, content, author_id) values ('5th generation', 'http://dummyimage.com/246x177.jpg/5fa2dd/ffffff', 'Enhanced heuristic extranet', 5);
insert into posts (title, img, content, author_id) values ('Cloned', 'http://dummyimage.com/126x219.bmp/ff4444/ffffff', 'Expanded context-sensitive moratorium', 6);
insert into posts (title, img, content, author_id) values ('Networked', 'http://dummyimage.com/182x137.bmp/5fa2dd/ffffff', 'Balanced zero defect artificial intelligence', 7);
insert into posts (title, img, content, author_id) values ('bi-directional', 'http://dummyimage.com/240x144.png/cc0000/ffffff', 'Digitized bi-directional artificial intelligence', 8);
insert into posts (title, img, content, author_id) values ('non-volatile', 'http://dummyimage.com/159x239.jpg/5fa2dd/ffffff', 'Adaptive radical hub', 9);
insert into posts (title, img, content, author_id) values ('Synergized', 'http://dummyimage.com/128x130.bmp/ff4444/ffffff', 'Persistent high-level encryption', 10);
insert into posts (title, img, content, author_id) values ('Distributed', 'http://dummyimage.com/217x136.jpg/5fa2dd/ffffff', 'Advanced maximized moratorium', 11);
insert into posts (title, img, content, author_id) values ('web-enabled', 'http://dummyimage.com/129x221.jpg/5fa2dd/ffffff', 'Grass-roots system-worthy implementation', 12);
insert into posts (title, img, content, author_id) values ('Mandatory', 'http://dummyimage.com/129x105.png/ff4444/ffffff', 'User-friendly transitional solution', 13);
insert into posts (title, img, content, author_id) values ('cohesive', 'http://dummyimage.com/175x165.jpg/cc0000/ffffff', 'Monitored tangible encoding', 14);
insert into posts (title, img, content, author_id) values ('approach', 'http://dummyimage.com/244x222.jpg/dddddd/000000', 'Object-based system-worthy encoding', 15);
insert into posts (title, img, content, author_id) values ('budgetary management', 'http://dummyimage.com/133x250.bmp/ff4444/ffffff', 'Inverse contextually-based help-desk', 16);
insert into posts (title, img, content, author_id) values ('Synergized', 'http://dummyimage.com/167x214.jpg/ff4444/ffffff', 'Adaptive systematic access', 17);
insert into posts (title, img, content, author_id) values ('Team-oriented', 'http://dummyimage.com/232x225.bmp/cc0000/ffffff', 'Multi-channelled responsive array', 18);
insert into posts (title, img, content, author_id) values ('time-frame', 'http://dummyimage.com/216x239.jpg/dddddd/000000', 'Profit-focused maximized matrices', 19);
insert into posts (title, img, content, author_id) values ('secured line', 'http://dummyimage.com/201x232.png/cc0000/ffffff', 'Profit-focused 5th generation open architecture', 20);
insert into posts (title, img, content, author_id) values ('Open-architected', 'http://dummyimage.com/190x124.jpg/dddddd/000000', 'Down-sized multimedia ability', 21);
insert into posts (title, img, content, author_id) values ('Graphical User Interface', 'http://dummyimage.com/127x129.png/cc0000/ffffff', 'User-friendly eco-centric pricing structure', 22);
insert into posts (title, img, content, author_id) values ('synergy', 'http://dummyimage.com/217x103.png/ff4444/ffffff', 'Intuitive scalable installation', 23);
insert into posts (title, img, content, author_id) values ('strategy', 'http://dummyimage.com/145x188.jpg/cc0000/ffffff', 'Progressive asymmetric model', 24);
insert into posts (title, img, content, author_id) values ('website', 'http://dummyimage.com/139x140.jpg/ff4444/ffffff', 'Public-key full-range solution', 25);
insert into posts (title, img, content, author_id) values ('Exclusive', 'http://dummyimage.com/214x154.bmp/ff4444/ffffff', 'Fundamental grid-enabled middleware', 26);
insert into posts (title, img, content, author_id) values ('Optional', 'http://dummyimage.com/120x109.png/ff4444/ffffff', 'Fully-configurable foreground leverage', 27);
insert into posts (title, img, content, author_id) values ('real-time', 'http://dummyimage.com/230x105.jpg/dddddd/000000', 'Visionary motivating open architecture', 28);
insert into posts (title, img, content, author_id) values ('help-desk', 'http://dummyimage.com/227x200.png/5fa2dd/ffffff', 'Multi-lateral heuristic intranet', 29);
insert into posts (title, img, content, author_id) values ('fresh-thinking', 'http://dummyimage.com/172x216.bmp/5fa2dd/ffffff', 'Profit-focused contextually-based neural-net', 30);
insert into posts (title, img, content, author_id) values ('structure', 'http://dummyimage.com/107x237.jpg/cc0000/ffffff', 'Synergistic neutral circuit', 31);
insert into posts (title, img, content, author_id) values ('approach', 'http://dummyimage.com/126x108.bmp/dddddd/000000', 'Assimilated heuristic middleware', 32);
insert into posts (title, img, content, author_id) values ('grid-enabled', 'http://dummyimage.com/245x165.jpg/5fa2dd/ffffff', 'Automated client-driven knowledge base', 33);
insert into posts (title, img, content, author_id) values ('internet solution', 'http://dummyimage.com/186x180.jpg/ff4444/ffffff', 'Integrated optimizing process improvement', 34);
insert into posts (title, img, content, author_id) values ('background', 'http://dummyimage.com/210x214.bmp/dddddd/000000', 'Progressive regional paradigm', 35);
insert into posts (title, img, content, author_id) values ('open system', 'http://dummyimage.com/146x247.bmp/ff4444/ffffff', 'Team-oriented mobile superstructure', 36);
insert into posts (title, img, content, author_id) values ('client-server', 'http://dummyimage.com/133x178.bmp/ff4444/ffffff', 'Seamless explicit architecture', 37);
insert into posts (title, img, content, author_id) values ('open architecture', 'http://dummyimage.com/216x115.jpg/ff4444/ffffff', 'Upgradable intermediate customer loyalty', 38);
insert into posts (title, img, content, author_id) values ('Business-focused', 'http://dummyimage.com/234x207.bmp/cc0000/ffffff', 'Adaptive executive moratorium', 39);
insert into posts (title, img, content, author_id) values ('needs-based', 'http://dummyimage.com/239x222.png/ff4444/ffffff', 'Object-based responsive hardware', 40);
insert into posts (title, img, content, author_id) values ('client-server', 'http://dummyimage.com/200x202.jpg/cc0000/ffffff', 'Extended mobile capability', 41);
insert into posts (title, img, content, author_id) values ('solution-oriented', 'http://dummyimage.com/176x165.bmp/ff4444/ffffff', 'Exclusive 24 hour synergy', 42);
insert into posts (title, img, content, author_id) values ('interface', 'http://dummyimage.com/224x126.png/dddddd/000000', 'Re-engineered secondary function', 43);
insert into posts (title, img, content, author_id) values ('alliance', 'http://dummyimage.com/218x225.png/ff4444/ffffff', 'Ameliorated uniform intranet', 44);
insert into posts (title, img, content, author_id) values ('fault-tolerant', 'http://dummyimage.com/227x118.bmp/cc0000/ffffff', 'Stand-alone optimal access', 45);
insert into posts (title, img, content, author_id) values ('Robust', 'http://dummyimage.com/187x199.bmp/cc0000/ffffff', 'Ameliorated optimal portal', 46);
insert into posts (title, img, content, author_id) values ('Pre-emptive', 'http://dummyimage.com/184x133.png/5fa2dd/ffffff', 'Vision-oriented radical architecture', 47);
insert into posts (title, img, content, author_id) values ('explicit', 'http://dummyimage.com/220x181.png/5fa2dd/ffffff', 'Persevering attitude-oriented installation', 48);
insert into posts (title, img, content, author_id) values ('object-oriented', 'http://dummyimage.com/210x194.jpg/dddddd/000000', 'Cross-platform solution-oriented matrix', 49);
insert into posts (title, img, content, author_id) values ('Reverse-engineered', 'http://dummyimage.com/145x215.bmp/ff4444/ffffff', 'Profound user-facing throughput', 50);
insert into posts (title, img, content, author_id) values ('upward-trending', 'http://dummyimage.com/162x250.bmp/dddddd/000000', 'Optional 24 hour matrices', 51);
insert into posts (title, img, content, author_id) values ('Open-architected', 'http://dummyimage.com/170x233.bmp/cc0000/ffffff', 'Total uniform concept', 52);
insert into posts (title, img, content, author_id) values ('24 hour', 'http://dummyimage.com/116x180.bmp/ff4444/ffffff', 'Horizontal regional ability', 53);
insert into posts (title, img, content, author_id) values ('Networked', 'http://dummyimage.com/194x221.bmp/ff4444/ffffff', 'Reduced methodical middleware', 54);
insert into posts (title, img, content, author_id) values ('hub', 'http://dummyimage.com/222x219.png/ff4444/ffffff', 'Virtual holistic middleware', 55);
insert into posts (title, img, content, author_id) values ('Horizontal', 'http://dummyimage.com/199x168.jpg/dddddd/000000', 'Object-based logistical synergy', 56);
insert into posts (title, img, content, author_id) values ('global', 'http://dummyimage.com/144x142.jpg/cc0000/ffffff', 'Digitized 3rd generation Graphic Interface', 57);
insert into posts (title, img, content, author_id) values ('functionalities', 'http://dummyimage.com/139x164.jpg/ff4444/ffffff', 'Down-sized interactive standardization', 58);
insert into posts (title, img, content, author_id) values ('grid-enabled', 'http://dummyimage.com/196x240.bmp/ff4444/ffffff', 'Upgradable eco-centric utilisation', 59);
insert into posts (title, img, content, author_id) values ('Upgradable', 'http://dummyimage.com/117x187.bmp/ff4444/ffffff', 'Implemented directional challenge', 60);
insert into posts (title, img, content, author_id) values ('utilisation', 'http://dummyimage.com/182x246.jpg/5fa2dd/ffffff', 'Programmable multi-tasking internet solution', 61);
insert into posts (title, img, content, author_id) values ('Organic', 'http://dummyimage.com/214x144.jpg/dddddd/000000', 'Innovative discrete parallelism', 62);
insert into posts (title, img, content, author_id) values ('local', 'http://dummyimage.com/198x235.png/cc0000/ffffff', 'Profound attitude-oriented functionalities', 63);
insert into posts (title, img, content, author_id) values ('executive', 'http://dummyimage.com/109x247.jpg/dddddd/000000', 'Programmable reciprocal synergy', 64);
insert into posts (title, img, content, author_id) values ('attitude-oriented', 'http://dummyimage.com/182x227.bmp/dddddd/000000', 'Operative interactive workforce', 65);
insert into posts (title, img, content, author_id) values ('contextually-based', 'http://dummyimage.com/193x242.jpg/cc0000/ffffff', 'Profit-focused neutral matrix', 66);
insert into posts (title, img, content, author_id) values ('scalable', 'http://dummyimage.com/145x204.bmp/5fa2dd/ffffff', 'Persistent holistic help-desk', 67);
insert into posts (title, img, content, author_id) values ('tertiary', 'http://dummyimage.com/210x167.jpg/ff4444/ffffff', 'Down-sized 4th generation throughput', 68);
insert into posts (title, img, content, author_id) values ('array', 'http://dummyimage.com/131x138.png/ff4444/ffffff', 'Secured user-facing infrastructure', 69);
insert into posts (title, img, content, author_id) values ('systemic', 'http://dummyimage.com/169x196.png/5fa2dd/ffffff', 'Advanced neutral middleware', 70);
insert into posts (title, img, content, author_id) values ('global', 'http://dummyimage.com/189x117.bmp/cc0000/ffffff', 'Cloned multimedia moderator', 71);
insert into posts (title, img, content, author_id) values ('Polarised', 'http://dummyimage.com/240x197.png/cc0000/ffffff', 'Configurable bandwidth-monitored strategy', 72);
insert into posts (title, img, content, author_id) values ('high-level', 'http://dummyimage.com/209x197.jpg/ff4444/ffffff', 'Optimized fault-tolerant moderator', 73);
insert into posts (title, img, content, author_id) values ('protocol', 'http://dummyimage.com/150x157.jpg/cc0000/ffffff', 'Reverse-engineered multimedia interface', 74);
insert into posts (title, img, content, author_id) values ('Intuitive', 'http://dummyimage.com/124x218.jpg/dddddd/000000', 'Organic didactic standardization', 75);
insert into posts (title, img, content, author_id) values ('internet solution', 'http://dummyimage.com/134x113.png/cc0000/ffffff', 'Phased analyzing focus group', 76);
insert into posts (title, img, content, author_id) values ('Progressive', 'http://dummyimage.com/125x110.jpg/5fa2dd/ffffff', 'Switchable analyzing architecture', 77);
insert into posts (title, img, content, author_id) values ('local', 'http://dummyimage.com/162x201.jpg/dddddd/000000', 'Automated attitude-oriented software', 78);
insert into posts (title, img, content, author_id) values ('access', 'http://dummyimage.com/102x108.png/cc0000/ffffff', 'Diverse solution-oriented policy', 79);
insert into posts (title, img, content, author_id) values ('fresh-thinking', 'http://dummyimage.com/237x193.bmp/dddddd/000000', 'Synergized dedicated approach', 80);
insert into posts (title, img, content, author_id) values ('Fundamental', 'http://dummyimage.com/153x159.png/cc0000/ffffff', 'Grass-roots foreground pricing structure', 81);
insert into posts (title, img, content, author_id) values ('Robust', 'http://dummyimage.com/190x224.png/cc0000/ffffff', 'Centralized well-modulated process improvement', 82);
insert into posts (title, img, content, author_id) values ('background', 'http://dummyimage.com/249x220.png/cc0000/ffffff', 'Streamlined system-worthy core', 83);
insert into posts (title, img, content, author_id) values ('leverage', 'http://dummyimage.com/241x175.png/dddddd/000000', 'Reverse-engineered coherent system engine', 84);
insert into posts (title, img, content, author_id) values ('exuding', 'http://dummyimage.com/225x248.bmp/cc0000/ffffff', 'Advanced systemic database', 85);
insert into posts (title, img, content, author_id) values ('needs-based', 'http://dummyimage.com/213x215.jpg/ff4444/ffffff', 'Vision-oriented multimedia budgetary management', 86);
insert into posts (title, img, content, author_id) values ('artificial intelligence', 'http://dummyimage.com/107x104.bmp/dddddd/000000', 'Devolved multi-state software', 87);
insert into posts (title, img, content, author_id) values ('Centralized', 'http://dummyimage.com/223x115.png/ff4444/ffffff', 'Enhanced upward-trending firmware', 88);
insert into posts (title, img, content, author_id) values ('heuristic', 'http://dummyimage.com/226x211.jpg/ff4444/ffffff', 'Operative maximized time-frame', 89);
insert into posts (title, img, content, author_id) values ('Profound', 'http://dummyimage.com/205x154.png/ff4444/ffffff', 'Cross-group value-added moratorium', 90);
